#+TITLE: Day to Day Notes on anything
#+AUTHOR: Paul Murray
* Notes
** Status reporting
*** PI objectives
**** 1. Returns experience for small employers with basic validataions developed and tested with a small group of employers
**** 2. Backdated returns experience for small employers with basic validations developed and tested with a small group of employers
**** 3. Translation of Rules, Policies and Act into logic for Returns. PoC Completed.
** Jira board
Based off the tech enablement updates I've been asking for create a board for each functional area, make each area an epic. That way, tasks or user stories can fit underneath them.

Entered on [2025-06-11 Wed 14:24]
  [[file:~/org/todo.org::*Create a jira board based off of the status reports I've gathered from the tech enablement function][Create a jira board based off of the status reports I've gathered from the tech enablement function]]

  [2025-07-27 Sun]
  [[file:::27]]
* Go Channels
  A channel in Go, is like a pipe that connects two people. 
  One person can put things into the pipe, and the other person takes things out

  -----
  How it works:

** if you put a toy into the pipe (ch <- toy), you have to wait until the other kid takes it out (<-ch)

** if the other kid tries to grab the toy before you have put it in, well, there is just nothing there for them to grab

   ch := make(chan string)
   go func() {
   ch <- "ball"
   }()
   
   toy := <- ch
   fmt.Println("Got the", toy)

  [2025-08-19 Tue]
  [[file:::31]]
